/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_RPC_CLIENT_H_
#define JSONRPC_CPP_STUB_RPC_CLIENT_H_
#if __cplusplus >= 201703L
#define throw(...)
#endif

#include <jsonrpccpp/client.h>

class rpc_client : public jsonrpc::Client
{
    public:
        rpc_client(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value processInputJson(const Json::Value& input) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["input"] = input;
            Json::Value result = this->CallMethod("processInputJson",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value dealing(const Json::Value& input) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["input"] = input;
            Json::Value result = this->CallMethod("dealing",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value wkRpcProcess(const Json::Value& input) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["input"] = input;
            Json::Value result = this->CallMethod("wkRpcProcess",p);
            return result;
        }
};

#endif //JSONRPC_CPP_STUB_RPC_CLIENT_H_
